- name: Install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: Ensure repo exists
  git:
    repo: "git@github.com:Dispelk9/dispelk9.github.io.git"
    dest: "{{base_repo}}/{{base_project}}"
    update: yes

- name: Copy dispelk9.github.io Repo to apache2
  copy:
    src: "{{base_repo}}/{{base_project}}"
    dest: "{{base_apache}}"
    force: no
    remote_src: yes 
    mode: 0755
- name: Copy apache config from template
  template:
    src: "templates/dispelk9.conf.j2"
    dest: "/etc/apache2/sites-available/{{project_config}}"
    mode: 0660
- name: Copy htaccess into the websites folder
  template:
    src: "templates/.htaccess.j2"
    dest: "{{base_apache}}/{{base_project}}"
    mode: 0660
- name: Activating VirtualHost file
  shell: cd /etc/apache2/sites-available/ | a2ensite {{project_config}}
- name: Deactivating default site
  shell: a2dissite 000-default.conf
- name: Ensure apache is running
  service:
    name: apache2
    state: reloaded