- name: Install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: Copy dispelk Repo to apache2
  copy:
    src: "{{base_repo}}/{{base_project}}"
    dest: "{{base_apache}}"
    force: no
    remote_src: yes 
    mode: 0660
- name: Copy apache config from template
  template:
    src: "templates/dispelk9.conf.j2"
    dest: "/etc/apache2/sites-available/{{project_config}}"
    mode: 0660
- name: Activating VirtualHost file
  shell: sudo a2ensite /etc/apache2/sites-available/{{project_config}}
- name: Ensure apache is running
  service:
    name: apache2
    state: reloaded