
---
- name: test pull
  hosts:
  - localhost
  tasks:
    - name: create new dir
      file:
        path: "/tmp/testap/"
        state: directory
    - name: copy text file
      copy:
        src:  "docker_sandbox/docker_debian/text"
        dest: "/tmp/testap/"
