- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes
  become: true
  become_user: root
 
- name: Remove apt lock file
  become: true
  become_user: root
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Install packages
  become: true
  become_user: root
  apt:
    package:
    - cloud-image-utils
    - fail2ban
    - git
    - ansible
    - openssh-server
    - openssh-client
    - qemu-kvm
    - libvirt-daemon-system 
    - libvirt-clients 
    - bridge-utils 
- name: Copy setup bridge template
  template:
    src: "templates/br0.netdev.j2"
    dest: "{{networkfolder}}/br0.netdev"
    force: no 
    mode: 0660
- name: Copy setup bound bridge template
  template:
    src: "templates/1-vhobr2-bind.network.j2"
    dest: "{{networkfolder}}/1-{{network_brd}}-bind.network"
    force: no
    mode: 0660
- name: Copy setup dhcp for bridge template
  template:
    src: "templates/2-vhobr2-dhcp.network.j2"
    dest: "{{networkfolder}}/2-{{network_brd}}-dhcp.network"
    force: no 
    mode: 0660

- name: Copy template for new virtual network 
  template:
    src: "templates/vhobr2-network.xml.j2"
    dest: "{{rootfolder}}/{{virt_network}}.xml"
    force: no
    mode: 0660
# - name: Destroy old network
#   become: true
#   become_user: root
#   command: |
#     virsh net-destroy vhobr2-network 
# - name: Undefine old network
#   become: true
#   become_user: root
#   command: |
#     virsh net-undefine vhobr2-network
# - name: Enable new network for kvms
#   become: true
#   become_user: root
#   command: |
#     virsh net-define /tmp/vhobr2-network.xml

# - name: Start new network for kvms
#   become: true
#   become_user: root
#   command: |
#     virsh start /tmp/vhobr2-network

# - name: Auto start new network for kvms
#   become: true
#   become_user: root
#   command: |
#     virsh autostart /tmp/vhobr2-network

- name: Enable systemd-networkd
  command: |
    systemctl enable systemd-networkd

- name: Start systemd-networkd
  command: |
    systemctl start systemd-networkd