- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Upgrade all packages on servers
  apt: upgrade=safe force_apt_get=yes

- name: Remove dependencies apt autoremove
  ansible.builtin.apt:
    autoremove: yes

- name: Run "apt-get clean"
  apt:
    autoclean: yes

 
- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Install packages
  apt:
    package:
    - cloud-image-utils
    - fail2ban
    - git
    - ansible
    - openssh-server
    - openssh-client

- name: Copy Dockerfile to vhodocker
  template:
    src: templates/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    force: yes
    mode: 0755

- name: Restart systemd-timesyncd
  command: |
    systemctl restart systemd-timesyncd.service