- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes
  become: true
  become_user: root

- name: Upgrade all packages on servers
  apt: upgrade=safe force_apt_get=yes

- name: Remove dependencies apt autoremove
  ansible.builtin.apt:
    autoremove: yes

- name: Run "apt-get clean"
  apt:
    autoclean: yes

 
- name: Remove apt lock file
  become: true
  become_user: root
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Install packages
  become: true
  become_user: root
  apt:
    package:
    - cloud-image-utils
    - fail2ban
    - git
    - ansible
    - openssh-server
    - openssh-client
