- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become_user: root

- name: Install required system packages
  apt:
    pkg:
      - docker-compose
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

# - name: Add Docker GPG apt Key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

# - name: Add Docker Repository
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu focal stable
#     state: present

# - name: Update apt and install docker-ce
#   apt:
#     name: docker-ce
#     state: latest
#     update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Copy Dockerfile to vhodocker
  template:
    src: templates/dockerfile_templates/Dockerfile.j2
    dest: /root/PaladiumDocker/Dockerfile
    force: no
    mode: 0755

- name: Pull the remote repo
  shell: git pull
  args:
    chdir: /root/PaladiumDocker/Paladium

- name: Remove all old containers
  shell: | 
    docker stop $(docker ps -aq) 
    docker rm $(docker ps -aq)

- name: Build the Docker image
  shell: docker build -t paladium_apache .
  args:
    chdir: /root/PaladiumDocker/

- name: Run the new apache image
  shell: docker run -d --name paladium-test -p {{ debian_ip_port}} paladium_apache
